# Payment Channels — build + IDL + client automation.

set shell := ["bash", "-uc"]

program_dir   := "program/payment_channels"
ts_client_dir := "clients/typescript"
program_id    := "CHNLxYvVA28MJP9PrFuDXccuoGXAx7jBacfLEkahyGsX"
idl_file      := program_dir / "idl/payment_channels.json"
raw_idl_file  := program_dir / "idl/payment_channels.raw.json"

default:
    @just --list

# ---------- setup ----------

# One-shot: install JS deps and verify local toolchain.
setup:
    #!/usr/bin/env bash
    set -euo pipefail
    for cmd in pnpm cargo just; do
        command -v "$cmd" >/dev/null || { echo "missing: $cmd"; exit 1; }
    done
    pnpm install
    echo "✓ setup complete; program id: {{program_id}}"

program-id:
    @echo "{{program_id}}"

# Keep program keypairs outside version control and pass them directly when
# deploying, e.g. `solana program deploy target/deploy/payment_channels.so
# --program-id <keypair>`. Builds and CI produce only the SBF artifact; `target/`
# remains ignored for any local `target/deploy/*-keypair.json` generated by
# Solana tooling.

# ---------- build ----------

build: build-program build-client

build-program:
    cd {{program_dir}} && cargo build-sbf
    @echo "✓ program built"

# Cluster builds select the per-cluster TREASURY_OWNER (see src/constants.rs) and
# enable the build-time guard: they fail to compile until that cluster's real owner
# replaces the 0xBEEF placeholder. `--no-default-features` drops the localnet default
# so only the target cluster feature is active.
build-devnet:
    cd {{program_dir}} && cargo build-sbf --no-default-features --features devnet
    @echo "✓ devnet program built"

build-testnet:
    cd {{program_dir}} && cargo build-sbf --no-default-features --features testnet
    @echo "✓ testnet program built"

build-mainnet-beta:
    cd {{program_dir}} && cargo build-sbf --no-default-features --features mainnet-beta
    @echo "✓ mainnet-beta program built"

# Raw IDL is emitted by build.rs, gated on the `idl` feature so plain
# `cargo build` / `cargo build-sbf` don't touch it. Rust Codama macros define
# the wire types; the visitors then add distribute's dynamic account tail,
# normalize the events to the nodes-from-anchor shape, and write the
# committed IDL.
generate-idl:
    cd {{program_dir}} && GENERATE_IDL="$RANDOM-$(date +%s)" cargo build --features idl
    pnpm exec codama run idl --idl {{raw_idl_file}}
    @echo "✓ IDL: {{idl_file}}"

generate-client: generate-idl
    pnpm run generate
    @echo "✓ clients generated"

build-client: generate-client
    cd {{ts_client_dir}} && pnpm run build
    @echo "✓ ts client built"

# ---------- test ----------

test: test-program test-client

test-program: generate-client
    cd {{program_dir}} && cargo test-sbf

test-client: generate-client
    cd {{ts_client_dir}} && pnpm run test

# Run the parameterized CU benchmark scenarios and emit bench_report.md
# next to Cargo.toml. `--test-threads=1` keeps logs interleaved-free and
# avoids contention; bench scenarios themselves only push to a Mutex so
# the report is correct either way.
bench: generate-client
    cd {{program_dir}} && \
        BENCH=1 BENCH_DATE="$(date -u +%Y-%m-%d)" \
        cargo test-sbf --test instructions benchmark::scenarios:: -- --test-threads=1

# Focused event-engine end-to-end run (litesvm). Loads the compiled .so
# and exercises the self-CPI Anchor-event wire format via the `open`
# instruction plus the `emit_event` validation surface.
events-e2e:
    cd {{program_dir}} && cargo test-sbf --test instructions event_engine_e2e::

# ---------- quality ----------

check: generate-client
    cargo fmt --all -- --check
    cargo clippy --all-targets -- -D warnings
    pnpm run format:check
    cd {{ts_client_dir}} && pnpm run typecheck

fmt:
    cargo fmt --all
    pnpm run format

# ---------- misc ----------

clean:
    rm -rf target
    rm -rf {{program_dir}}/idl
    rm -rf clients/rust/src/generated
    rm -rf clients/typescript/src/generated
    rm -rf clients/typescript/dist
    rm -rf node_modules clients/*/node_modules

# ---------- deploy / verify / on-chain IDL ----------
#
# These recipes PREPARE and run
# deterministic builds + on-chain operations; the irreversible, SOL-spending
# steps (deploy / idl upload / verify) require you to pass the keypairs and are
# meant to be run by a human with eyes on the output.
#
# One-time tool install:
#   cargo install solana-verify                 # deterministic docker build + verification
#   # program-metadata CLI: see github.com/solana-program/program-metadata
#   # Docker must be running (solana-verify build executes in a container).
#
# HARD PREREQUISITES before any cluster deploy (the build will refuse otherwise):
#   1. constants.rs: set the real TREASURY_OWNER for the target cluster — the
#      0xBEEF placeholder trips a compile-time guard on devnet/testnet/mainnet.
#   2. `program_id` below MUST equal declare_id! in src/lib.rs AND the program
#      keypair you control. The committed IDL embeds this address, so after any
#      change run `just generate-client` and commit.
#   3. Commit + push to the public repo — verified builds verify a pushed commit.

repo_url    := "https://github.com/Moonsong-Labs/solana-payment-channels"
lib_name    := "payment_channels"
mainnet_url := "https://api.mainnet-beta.solana.com"
devnet_url  := "https://api.devnet.solana.com"
# Pin the verifiable-build image to a platform-tools that supports edition 2024
# (the default image ships Cargo 1.84, which predates it). 3.1.13 matches the
# local `solana --version`. The same image is recorded in the verification PDA
# so the remote (OtterSec) build reproduces the on-chain binary.
base_image  := "solanafoundation/solana-verifiable-build:3.1.13"

# Deterministic, container-based build for a cluster (default mainnet-beta) and
# print the executable hash. The resulting target/deploy/payment_channels.so is
# the exact byte image you deploy and that verification re-derives.
verified-build cluster="mainnet-beta":
    solana-verify build --library-name {{lib_name}} \
        --base-image {{base_image}} \
        --cargo-build-sbf-args="--no-default-features --features {{cluster}}"
    @echo "local executable hash:"
    solana-verify get-executable-hash target/deploy/{{lib_name}}.so

# On-chain program hash, to cross-check against the local build hash above.
# Override the endpoint with RPC_URL=... (the public mainnet RPC is unreliable).
program-hash-mainnet:
    #!/usr/bin/env bash
    set -euo pipefail
    solana-verify get-program-hash -u "${RPC_URL:-{{mainnet_url}}}" {{program_id}}

program-hash-devnet:
    solana-verify get-program-hash -u {{devnet_url}} {{program_id}}

# FIRST mainnet deploy only. Creates the program account at the PROGRAM_KEYPAIR
# address (must equal {{program_id}}) and sets DEPLOYER_KEYPAIR as the upgrade
# authority. Build with `just verified-build` first.
deploy-mainnet-initial:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${PROGRAM_KEYPAIR:?set PROGRAM_KEYPAIR=path/to/program-account-keypair.json}"
    : "${DEPLOYER_KEYPAIR:?set DEPLOYER_KEYPAIR=path/to/funded-payer-and-authority.json}"
    test -f target/deploy/{{lib_name}}.so || { echo "run 'just verified-build' first"; exit 1; }
    test "$(solana address -k "$PROGRAM_KEYPAIR")" = "{{program_id}}" \
        || { echo "PROGRAM_KEYPAIR address != {{program_id}}"; exit 1; }
    RPC="${RPC_URL:-{{mainnet_url}}}"
    echo "deploying via $RPC (set RPC_URL to a dedicated endpoint if this is the public RPC)"
    solana program deploy -u "$RPC" target/deploy/{{lib_name}}.so \
        --program-id "$PROGRAM_KEYPAIR" \
        --keypair "$DEPLOYER_KEYPAIR" \
        --upgrade-authority "$DEPLOYER_KEYPAIR" \
        --with-compute-unit-price 50000 --max-sign-attempts 100 --use-rpc

# Upgrade an already-deployed mainnet program. DEPLOYER_KEYPAIR must be the
# current upgrade authority.
deploy-mainnet-upgrade:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${DEPLOYER_KEYPAIR:?set DEPLOYER_KEYPAIR=path/to/upgrade-authority.json}"
    test -f target/deploy/{{lib_name}}.so || { echo "run 'just verified-build' first"; exit 1; }
    RPC="${RPC_URL:-{{mainnet_url}}}"
    solana program deploy -u "$RPC" target/deploy/{{lib_name}}.so \
        --program-id {{program_id}} \
        --keypair "$DEPLOYER_KEYPAIR" \
        --with-compute-unit-price 50000 --max-sign-attempts 100 --use-rpc

# Upload / refresh the on-chain IDL via the Program Metadata program.
# IDL_AUTHORITY_KEYPAIR is the program upgrade authority (or a delegated
# metadata authority). Regenerates the IDL first so it matches the source.
deploy-idl-mainnet: generate-idl
    #!/usr/bin/env bash
    set -euo pipefail
    : "${IDL_AUTHORITY_KEYPAIR:?set IDL_AUTHORITY_KEYPAIR=path/to/authority.json}"
    program-metadata write idl {{program_id}} {{idl_file}} \
        --keypair "$IDL_AUTHORITY_KEYPAIR" --rpc "${RPC_URL:-{{mainnet_url}}}"

deploy-idl-devnet: generate-idl
    #!/usr/bin/env bash
    set -euo pipefail
    : "${IDL_AUTHORITY_KEYPAIR:?set IDL_AUTHORITY_KEYPAIR=path/to/authority.json}"
    program-metadata write idl {{program_id}} {{idl_file}} \
        --keypair "$IDL_AUTHORITY_KEYPAIR" --rpc {{devnet_url}}

# Submit the deployed mainnet program for verified-build verification against
# the public repo at the CURRENT commit. Run on a clean, pushed tree. The
# feature flags MUST match those used for the deployed build, and are forwarded
# to the remote (OtterSec) builder; confirm an end-to-end hash match on devnet
# first.
verify-mainnet:
    #!/usr/bin/env bash
    set -euo pipefail
    test -z "$(git status --porcelain)" || { echo "working tree dirty; commit + push first"; exit 1; }
    solana-verify verify-from-repo {{repo_url}} -u "${RPC_URL:-{{mainnet_url}}}" \
        --program-id {{program_id}} \
        --library-name {{lib_name}} \
        --base-image {{base_image}} \
        --commit-hash "$(git rev-parse HEAD)" \
        --cargo-build-sbf-args="--no-default-features --features mainnet-beta"
