# Payment Channels — build + IDL + client automation.

set shell := ["bash", "-uc"]

program_dir   := "program/payment_channels"
ts_client_dir := "clients/typescript"
program_id    := "CQAyft83tN1w2bRofB5PZ79eVDU2xZUVo43LU1qL4zRg"
idl_file      := program_dir / "idl/payment_channels.json"
raw_idl_file  := program_dir / "idl/payment_channels.raw.json"

default:
    @just --list

# ---------- setup ----------

# One-shot: install JS deps and verify local toolchain.
setup:
    #!/usr/bin/env bash
    set -euo pipefail
    for cmd in pnpm cargo just; do
        command -v "$cmd" >/dev/null || { echo "missing: $cmd"; exit 1; }
    done
    pnpm install
    echo "✓ setup complete; program id: {{program_id}}"

program-id:
    @echo "{{program_id}}"

# Keep program keypairs outside version control and pass them directly when
# deploying, e.g. `solana program deploy target/deploy/payment_channels.so
# --program-id <keypair>`. Builds and CI produce only the SBF artifact; `target/`
# remains ignored for any local `target/deploy/*-keypair.json` generated by
# Solana tooling.

# ---------- build ----------

build: build-program build-client

build-program:
    cd {{program_dir}} && cargo build-sbf
    @echo "✓ program built"

# Cluster builds select the per-cluster TREASURY_OWNER (see src/constants.rs) and
# enable the build-time guard: they fail to compile until that cluster's real owner
# replaces the 0xBEEF placeholder. `--no-default-features` drops the localnet default
# so only the target cluster feature is active.
build-devnet:
    cd {{program_dir}} && cargo build-sbf --no-default-features --features devnet
    @echo "✓ devnet program built"

build-mainnet:
    cd {{program_dir}} && cargo build-sbf --no-default-features --features mainnet
    @echo "✓ mainnet program built"

# Raw IDL is emitted by build.rs, gated on the `idl` feature so plain
# `cargo build` / `cargo build-sbf` don't touch it. Rust Codama macros define
# the wire types; the remaining visitor only adds distribute's dynamic account
# tail and writes the committed IDL.
generate-idl:
    cd {{program_dir}} && GENERATE_IDL="$RANDOM-$(date +%s)" cargo build --features idl
    pnpm exec codama run idl --idl {{raw_idl_file}}
    @echo "✓ IDL: {{idl_file}}"

generate-client: generate-idl
    pnpm run generate
    @echo "✓ clients generated"

build-client: generate-client
    cd {{ts_client_dir}} && pnpm run build
    @echo "✓ ts client built"

# ---------- test ----------

test: test-program test-client

test-program: generate-client
    cd {{program_dir}} && cargo test-sbf

test-client: generate-client
    cd {{ts_client_dir}} && pnpm run test

# Run the parameterized CU benchmark scenarios and emit bench_report.md
# next to Cargo.toml. `--test-threads=1` keeps logs interleaved-free and
# avoids contention; bench scenarios themselves only push to a Mutex so
# the report is correct either way.
bench: generate-client
    cd {{program_dir}} && \
        BENCH=1 BENCH_DATE="$(date -u +%Y-%m-%d)" \
        cargo test-sbf --test instructions benchmark::scenarios:: -- --test-threads=1

# Focused event-engine end-to-end run (litesvm). Loads the compiled .so
# and exercises the self-CPI Anchor-event wire format via the `open`
# instruction plus the `emit_event` validation surface.
events-e2e:
    cd {{program_dir}} && cargo test-sbf --test instructions event_engine_e2e::

# ---------- quality ----------

check: generate-client
    cargo fmt --all -- --check
    cargo clippy --all-targets -- -D warnings
    pnpm run format:check
    cd {{ts_client_dir}} && pnpm run typecheck

fmt:
    cargo fmt --all
    pnpm run format

# ---------- misc ----------

clean:
    rm -rf target
    rm -rf {{program_dir}}/idl
    rm -rf clients/rust/src/generated
    rm -rf clients/typescript/src/generated
    rm -rf clients/typescript/dist
    rm -rf node_modules clients/*/node_modules
